### ISSUE TITLE
If string contains '.' it breaks.

### ISSUE THREAD

**Issue by thebluefowl** [sarathsp06/gojson#1]

**Comment by thebluefowl** [comment]
main.go uses: keys := strings.Split(key, ".") to separate the command.

**Comment by sarathsp06** [comment]
Would adding a feature of quoting keys with . using `'` be a better alternative ? 

The it would be 
* Default behaviour split by `.`
* If there are `'` anything in between them are considered as one key
* Keys should still be sprated with `.` but can be wrapped using `'` for escaping `.` inside ke
